version: '3.8'
services:
  descomplicando-nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: descomplicando-nestjs
    restart: always
    entrypoint: sh -c "yarn && yarn start:dev"
    environment:
      NGINX_PORT: ${NGINX_PORT}
      POSTGRES_HOST: descomplicando-nestjs-db
    networks:
      - descomplicando-nestjs-network
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - descomplicando-nestjs-db
    ports:
      - ${PORT}:${PORT}

  descomplicando-nestjs-db:
    image: postgres:13.3-alpine
    container_name: descomplicando-nestjs-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - descomplicando-nestjs-data:/var/lib/postgresql/data
    networks:
      - descomplicando-nestjs-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    expose:
      - ${NGINX_PORT}
    networks:
      - descomplicando-nestjs-network
    links:
      - descomplicando-nestjs

volumes:
  descomplicando-nestjs-data:

networks:
  descomplicando-nestjs-network:
